# -*- coding: utf-8 -*-
"""Data Analysis Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVvUxkgtsP9M8NCrGP2ykjsRPphC6ji6
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

FilePath = '/content/leads_basic_details.csv'

Data = pd.read_csv(FilePath)

Data.head()

Data.isnull().sum()
Data.info()

Data

Data.shape

Data.dtypes

Data.isnull().sum()

df1_outlier = Data[Data.age>Data.age.quantile(0.90)]
df1_outlier
Data = Data.drop([df1_outlier.index[0] , df1_outlier.index[1]])

Data['current_education'].replace({'Intermediate Completed':'Intermediate'}, inplace=True)

sns.regplot(x="age", y="age",data=Data,fit_reg=False)

Data.info()

sns.countplot(x='age',data=Data)

sns.countplot(x='gender',data=Data)

countplt, ax = plt.subplots(figsize = (10,7))
ax =sns.countplot(x='current_city',data=Data)

countplt, ax = plt.subplots(figsize = (10,7))
ax =sns.countplot(x = 'lead_gen_source', data=Data)

countplt, ax = plt.subplots(figsize = (10,7))
ax =sns.countplot(x = 'current_city', data=Data)